# Generated by Django 4.2.11 on 2025-07-15 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wildfire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_id', models.CharField(db_index=True, help_text='Unique identifier for the wildfire incident.', max_length=100, unique=True)),
                ('fire_name', models.CharField(blank=True, help_text='Name of the wildfire incident.', max_length=200)),
                ('latitude', models.FloatField(help_text='Latitude of the wildfire incident location.')),
                ('longitude', models.FloatField(help_text='Longitude of the wildfire incident location.')),
                ('location_description', models.TextField(blank=True, help_text='Description of the wildfire incident location.')),
                ('size_hectares', models.FloatField(default=0, help_text='Size of the wildfire incident in hectares.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONTAINED', 'Contained'), ('UNDER_CONTROL', 'Under Control'), ('OUT', 'Out')], default='ACTIVE', help_text='Current status of the wildfire incident.', max_length=50)),
                ('detected_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the wildfire incident was detected.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Date and time when the wildfire incident was last updated.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the wildfire incident record was created.')),
                ('cause', models.CharField(blank=True, max_length=100)),
                ('data_source', models.CharField(default='NASA FIRMS', max_length=50)),
            ],
            options={
                'ordering': ['-detected_date'],
                'indexes': [models.Index(fields=['status', 'detected_date'], name='fires_wildf_status_cc1c2d_idx')],
            },
        ),
    ]
