# Generated by Django 4.2.11 on 2025-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('well_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('well_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='ABANDONED', max_length=50)),
                ('abandonment_date', models.DateField(blank=True, null=True)),
                ('licensee', models.CharField(blank=True, max_length=200)),
                ('surface_location', models.CharField(blank=True, max_length=200)),
                ('ground_elevation', models.FloatField(blank=True, null=True)),
                ('total_depth', models.FloatField(blank=True, help_text='Depth in meters', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.CharField(default='AER', max_length=50)),
            ],
            options={
                'ordering': ['well_id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fires_aband_latitud_6caa36_idx'), models.Index(fields=['status', 'well_type'], name='fires_aband_status_548def_idx')],
            },
        ),
    ]
